[general]
fallback_to_native = true
profile = profile.unified_standard

#########################################################
################## Profile Section ##################
#########################################################

############# unified #############
[profile.unified_standard]
repos = repo.base_standard,repo.base_standard_debug,repo.unified_standard,repo.unified_standard_debug

[profile.unified_emulator]
repos = repo.base_standard,repo.base_standard_debug,repo.unified_emulator,repo.unified_emulator_debug

#########################################################
################## Repo Section##################
#########################################################

############# base #############
[repo.base_standard]
url = https://download.tizen.org/releases/milestone/TIZEN/Tizen-10.0/Tizen-10.0-Base/tizen-10.0-base_20251028.083647/repos/standard/packages/
[repo.base_standard_debug]
url = https://download.tizen.org/releases/milestone/TIZEN/Tizen-10.0/Tizen-10.0-Base/tizen-10.0-base_20251028.083647/repos/standard/debug/

############# unified #############
[repo.unified_standard]
url = https://download.tizen.org/releases/milestone/TIZEN/Tizen-10.0/Tizen-10.0-Unified/tizen-10.0-unified_20251028.114828/repos/standard/packages/
[repo.unified_standard_debug]
url = https://download.tizen.org/releases/milestone/TIZEN/Tizen-10.0/Tizen-10.0-Unified/tizen-10.0-unified_20251028.114828/repos/standard/debug/

[repo.unified_emulator]
url = https://download.tizen.org/releases/milestone/TIZEN/Tizen-10.0/Tizen-10.0-Unified/tizen-10.0-unified_20251028.114828/repos/emulator/packages/
[repo.unified_emulator_debug]
url = https://download.tizen.org/releases/milestone/TIZEN/Tizen-10.0/Tizen-10.0-Unified/tizen-10.0-unified_20251028.114828/repos/emulator/debug/
