export TIZEN_PROJECT=$HOME/tizen
export PATH=$TIZEN_PROJECT/.dotnet:$PATH

export TIZEN_STUDIO=$TIZEN_PROJECT/.tizen-studio
export PATH=$TIZEN_STUDIO/tools:$TIZEN_STUDIO/tools/emulator/bin:$TIZEN_STUDIO/package-manager:$PATH
